language: generic
deploy:
  provider: gcs
  access_key_id: GOOGBITGKSTHYZST362P
  secret_access_key:
    secure: HCj6vUfpHXJ1oquH8Mcxx2yHvcNuFRsNFT+2Bn0s11bSgv4G99mLMvkWyBTDFGF6m/gB321OOKd+7Cb56Tr5qSKnOKFNFMMeaG80j5pyiKyFMonRsNaOSJ8iCG51XJHQtKnvBOdKaEj6ploIcMF6qXdRPjPLSPAev6XJacwFmQgB6Z8OgmXa5PMSFEqL7WAIc4jus0dqGa97FO/SMVD1eeON50Ksijy/ZJJ5Y4fqNl/5IxTomm262RWh00ltgpC/7m7UiBBSNp9SGJfwqUOv+AzhvW8vB2xjzCQ0chxEAwNE49naomBCJ7fOvHOVYg0RzhH4yfxmtxkFFGcnR8NZMheJjhzhUrNOd0CzQ+Xyqr/PESMeEYUARvytu9GngDhJ5Zj6PD+z6gIyymqevFDTKicfnbcdP4K+6s5BpNRBpzd4pvXAXqh1erlQzfP6gBMVyTJHxuXusDvDAvnBr1+RAQMQExR9Gu/XzPfnnZj3uZwcN7SljumQryysR6MR0hV7kIbfqYaiX0Mq3794Z8gOsuHJX+KjfZGzBwI3PXFZKiYlQHCfqatmOQsrr9AsUDQgNYp2itVGfaTRwVJr1th+6aRvDYCh39GiISJd16sjDa0OVa0Fph1CNwhLIRCRYP/BPvimG+4ts4jxZQbxxOHWObPX+dMZNR3PjaujVbo/F1I=
  bucket: beta2-inet.emmerson.pl
  on:
    repo: GrupaEmmerson/inet
  skip_cleanup: true
  acl: public-read
  cache_control: "max-age=60"
