language: generic
deploy:
  provider: gcs
  access_key_id: GOOGBITGKSTHYZST362P
  secret_access_key:
    secure: IzMI7LfRlYOIrUqQQ7DRduK4hUmH7Rl/xkj7zXp7NG2RUrTAc7lkVGxrYF7eXnMP5/l8atRZFH6fSu1dBDexUlwvoK9u2sbXHY44mV8nlysYn5QzCaA8p7f6RQ0z36jvokusIzsRMrvErQf/7so8MYcnhzErZ6biCNcEWWFe5uRpFWCdGh1+SytDJF8dbNAPb
KgJs3u/locOGSQPdG8hQF6LZs7vUtUAxtVyUjmOf2gDV53TTIJ9+eWswbG5X8aMI0/W4w5n9iU2100dL3ES5jAW9XSRi2NekX/brnMd4dnK43Paq91GID1Xf9sZC0fH1osTkfFZ8BXAqsqcqrYfAqpGbfFUE6CpVjWUpcj7DDW8mVhQdARK4X9zI9pzvxGh1sQ2hZ72VNxNVh
0tqfpFB1Jgb8v5MvugaiBMhMxGvu8ylijGPuuHepCsCSqXtN+EHBezq+P1rCuufCKERCkuEoWza94oX5fmt4zAdssA7ekktgScj99TX0LJhQKdKK7b/xdKreYzz2aOzCnSXccIatCG8Vfs6dBthu7JaldhtF7qq8282t9FfbsD7KEw7tCG71H0IFLG6HV7OdxfrradVK/L8RX
3qVeeJ6WqrCaHEOxFFi1vuQRtPyqHAwpGOO1mNhu0T3x/PUe1NfPK8jrJLZ19kg4hylPJJcfCS95pnhc=
  bucket: beta2-inet.emmerson.pl
  on:
    repo: GrupaEmmerson/inet
  cache_control: max-age=60
